### ISSUE TITLE
Correct Image Style for the Carousel Paragraph

### ISSUE THREAD

**Issue by ashooner** [uky-web/uky_base#6]
From Justin:

Recreate:  
Add a carousel paragraph to a page.  
  
Intended Result:  
Images appear on the page as full width content at an appropriate resolution.

Actual Result:  
Images appear compressed/blurry.
  
Notes:  
The carousel image style is using the responsive image style "Partial Width" which sets a maximum width of 650px on the image. This should be changed to the "Content Width" responsive style.

Made the change by request on pattersonschool.uky.dev

**Comment by justin-sumner** [comment]
The Carousel paragraph uses the eck media bundle which has view modes for default and full width the default uses the partial width responsive image style and the full width uses the full content width responsive image style. I switched it to full width.
